### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by C-ollins** [decred/dcrwallet#1225]
I got this error while trying out spv on mainnet.

```
2018-08-07 17:45:21.719 [INF] SYNC: Connected 2000 blocks, new tip 0000000000000000f4e26a1f579d1a32f369238a26661b8eaab6381be7938019, height 254000, date 2018-07-06 00:06:37 +0100 WAT
2018-08-07 17:45:30.053 [INF] SYNC: Connected 2000 blocks, new tip 000000000000000149430dd2b89a16a05891a883dfeec8ef88fbfd1530492fd8, height 256000, date 2018-07-12 23:12:49 +0100 WAT
2018-08-07 17:45:45.464 [INF] SYNC: Connected 2000 blocks, new tip 000000000000000049c27d479e5f758a3a4ef124e19da8f2e74e234cf6b77676, height 258000, date 2018-07-19 21:20:05 +0100 WAT
2018-08-07 17:46:03.354 [INF] SYNC: Connected 2000 blocks, new tip 0000000000000000474d388aa0248402c50376d66eee6c5b12c500570126ad69, height 260000, date 2018-07-26 19:16:36 +0100 WAT
2018-08-07 17:46:16.056 [WRN] SYNC: Lost peer 45.76.174.205:9108: remotepeer(45.76.174.205:9108).GetCFilter(00000000000000008f3a66676edcbc68835c864a1bb8f82c2a354f1dfb4916eb): I/O error: peer appears stalled
2018-08-07 17:46:16.869 [INF] SYNC: New peer 107.179.246.222:9108 /dcrwire:0.3.0/dcrd:1.2.0/ SFNodeNetwork|SFNodeBloom|SFNodeCF
2018-08-07 17:46:20.621 [INF] SYNC: Connected 2000 blocks, new tip 00000000000000006f66a7a62a86d72c4b883cdfc731d79603c6cd36a980f65f, height 262000, date 2018-08-02 16:55:13 +0100 WAT
2018-08-07 17:46:38.322 [INF] SYNC: Connected 1453 blocks, new tip 0000000000000000292b6eadd2033c65609989b29b824f6db357073e32e0893d, height 263453, date 2018-08-07 17:38:01 +0100 WAT
2018-08-07 17:46:38.599 [INF] WLLT: Discovering used accounts
2018-08-07 17:46:59.872 [INF] SYNC: Connected block 00000000000000006e3007af711c1c6e8e85f371aaef20c97ecea237d01c93f7, height 263454, 0 wallet transaction(s)
panic: runtime error: index out of range

goroutine 1452647 [running]:
github.com/decred/dcrwallet/spv.(*Syncer).getHeaders(0xc4201563c0, 0xde9360, 0xc432f2d240, 0xc42f92fa40, 0x1, 0x1)
	/home/collins/go/src/github.com/decred/dcrwallet/spv/sync.go:903 +0x12bb
github.com/decred/dcrwallet/spv.(*Syncer).startupSync(0xc4201563c0, 0xde9360, 0xc432f2d240, 0xc42f92fa40, 0x4349b8, 0xd83a10)
	/home/collins/go/src/github.com/decred/dcrwallet/spv/sync.go:1038 +0x1fb
github.com/decred/dcrwallet/spv.(*Syncer).connectToCandidates.func1.2(0xc4201563c0, 0xde9360, 0xc432f2d240, 0xc42f92fa40, 0xc42a22a780)
	/home/collins/go/src/github.com/decred/dcrwallet/spv/sync.go:335 +0x4d
created by github.com/decred/dcrwallet/spv.(*Syncer).connectToCandidates.func1
	/home/collins/go/src/github.com/decred/dcrwallet/spv/sync.go:334 +0x5f0
```

**Comment by C-ollins** [comment]
Error still occurs from v1.1.1 of spv. The crash is very rare so it’ll be very hard to recreate.

**Comment by jrick** [comment]
I believe #1488 fixes this.

**Comment by jrick** [comment]
Likely fixed.  Reopen with more details if you continue to see this.
