### ISSUE TITLE
Crash when syncing

### ISSUE THREAD

**Issue by peterzen** [decred/dcrwallet#1435]
```
2019-04-08 12:01:14.578 [INF] DCRW: Version 1.4.0+release (Go version go1.11.5 linux/arm)
2019-04-08 12:01:21.057 [INF] WLLT: Opened wallet
Enter private passphrase: 
Incorrect password entered. Please try again.
Enter private passphrase: 
2019-04-08 12:01:47.526 [INF] WLLT: The wallet has been unlocked without a time limit
2019-04-08 12:01:47.673 [INF] DCRW: gRPC server listening on 127.0.0.1:9111
2019-04-08 12:01:47.673 [INF] DCRW: gRPC server listening on [::1]:9111
2019-04-08 12:01:47.673 [INF] RPCS: Listening on 127.0.0.1:9110
2019-04-08 12:01:47.673 [INF] DCRW: Attempting RPC client connection to dcrd:9109
2019-04-08 12:01:48.098 [INF] SYNC: Established connection to RPC server dcrd:9109
2019-04-08 12:01:48.153 [INF] SYNC: Headers synced through block 00000000000000000caf81e7d411b5711682d9a3af90dc3947c1fa2c188f7e14 height 331248
2019-04-08 12:01:48.153 [INF] SYNC: Transactions synced through block 00000000000000000caf81e7d411b5711682d9a3af90dc3947c1fa2c188f7e14 height 331248
panic: runtime error: index out of range

goroutine 45 [running]:
github.com/boltdb/bolt.(*leafPageElement).key(...)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/page.go:120
github.com/boltdb/bolt.(*Cursor).nsearch.func2(0x1934, 0x66d4dd01)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:334 +0xa4
sort.Search(0x3269, 0x1d2bb10, 0x8)
	/home/build/go/src/sort/search.go:66 +0x54
github.com/boltdb/bolt.(*Cursor).nsearch(0x1d2bdb4, 0x29a8960, 0x20, 0x20)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:333 +0xb4
github.com/boltdb/bolt.(*Cursor).search(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0x32dd, 0x0)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:263 +0x154
github.com/boltdb/bolt.(*Cursor).searchPage(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0x4918f000)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:314 +0x114
github.com/boltdb/bolt.(*Cursor).search(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0x2554, 0x0)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:271 +0x130
github.com/boltdb/bolt.(*Cursor).searchPage(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0x5061f000)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:314 +0x114
github.com/boltdb/bolt.(*Cursor).search(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0x99e4, 0x0)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:271 +0x130
github.com/boltdb/bolt.(*Cursor).searchPage(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0x514ad000)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:314 +0x114
github.com/boltdb/bolt.(*Cursor).search(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0xa872, 0x0)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:271 +0x130
github.com/boltdb/bolt.(*Cursor).seek(0x1d2bdb4, 0x29a8960, 0x20, 0x20, 0x0, 0x0, 0x1c14000, 0x6e7bf8, 0x746a10, 0x66c3b230, ...)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:159 +0xa0
github.com/boltdb/bolt.(*Bucket).Get(0x23ad800, 0x29a8960, 0x20, 0x20, 0x66c3b230, 0x23ad800, 0x23ad800)
	/home/build/.go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:267 +0x9c
github.com/decred/dcrwallet/wallet/internal/bdb.(*bucket).Get(0x23ad800, 0x29a8960, 0x20, 0x20, 0x66c3b230, 0x23ad800, 0x23ad7e0)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.2.0/internal/bdb/db.go:176 +0x34
github.com/decred/dcrwallet/wallet/udb.existsBlockHeader(0x66c3b230, 0x23ad7e0, 0x29a8960, 0x20, 0x20, 0x23ad7e0, 0x204ab60, 0x2074690)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.2.0/udb/txdb.go:478 +0x74
github.com/decred/dcrwallet/wallet/udb.(*Store).BlockInMainChain(0x2080010, 0x9a87f8, 0x2c87ef0, 0x29a8960, 0x1d2be68)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.2.0/udb/txmined.go:830 +0x7c
github.com/decred/dcrwallet/wallet.(*Wallet).BlockInMainChain.func1(0x9a87f8, 0x2c87ef0, 0x9a87f8, 0x2c87ef0)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.2.0/wallet.go:510 +0x48
github.com/decred/dcrwallet/wallet/walletdb.View(0x9ab8f0, 0x1ff86c0, 0x1d2bea4, 0x0, 0x0)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.2.0/walletdb/interface.go:213 +0xa4
github.com/decred/dcrwallet/wallet.(*Wallet).BlockInMainChain(0x2038300, 0x29a8960, 0x0, 0x0, 0x0)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.2.0/wallet.go:509 +0x6c
github.com/decred/dcrwallet/chain.(*RPCSyncer).startupSync(0x206fba0, 0x9ab430, 0x206fd40, 0x3b5c68, 0x4)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/chain@v1.1.1/sync.go:507 +0x474
github.com/decred/dcrwallet/chain.(*RPCSyncer).Run.func1(0x4, 0x8fcbe0)
	/home/build/.go/pkg/mod/github.com/decred/dcrwallet/chain@v1.1.1/sync.go:189 +0x68
golang.org/x/sync/errgroup.(*Group).Go.func1(0x1c22780, 0x206fd80)
	/home/build/.go/pkg/mod/golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f/errgroup/errgroup.go:57 +0x48
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/build/.go/pkg/mod/golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f/errgroup/errgroup.go:54 +0x50
```

dcrwallet.conf:

```
[Application Options]
username=rpc
password=xxxxx
promptpass=1

enableticketbuyer=0
enablevoting=0

txfee=0.05
ticketbuyer.votingaddress=xxxxxxx


rpclisten=127.0.0.1:9110 

cafile=~/.dcrwallet/dcrd-priv.cert
rpcconnect=dcrd:9109
dcrdusername=dcrd
dcrdpassword=xxxxx
```

The wallet can be opened read only

`dcrwallet --rpcconnect=localhost`
```
2019-04-08 12:27:49.571 [INF] DCRW: Version 1.4.0+release (Go version go1.11.5 linux/arm)
2019-04-08 12:27:56.048 [INF] WLLT: Opened wallet
Enter private passphrase:
2019-04-08 12:28:09.090 [INF] WLLT: The wallet has been unlocked without a time limit
2019-04-08 12:28:09.236 [INF] DCRW: gRPC server listening on 127.0.0.1:9111
2019-04-08 12:28:09.237 [INF] DCRW: Attempting RPC client connection to localhost:9109
2019-04-08 12:28:09.237 [INF] DCRW: gRPC server listening on [::1]:9111
2019-04-08 12:28:09.237 [INF] RPCS: Listening on 127.0.0.1:9110
2019-04-08 12:28:09.238 [ERR] SYNC: Connection attempt failed: dial tcp [::1]:9109: connect: connection refused
```

**Comment by peterzen** [comment]
When running on latest master:

```
2019-04-08 14:19:34.656 [INF] DCRW: Version 1.5.0-pre+dev (Go version go1.12 linux/arm)
2019-04-08 14:19:41.095 [INF] WLLT: Opened wallet
Enter private passphrase:
2019-04-08 14:19:53.417 [INF] WLLT: The wallet has been unlocked without a time limit
2019-04-08 14:19:53.632 [INF] DCRW: gRPC server listening on 127.0.0.1:9111
2019-04-08 14:19:53.632 [INF] DCRW: gRPC server listening on [::1]:9111
2019-04-08 14:19:53.647 [INF] RPCS: Listening on 127.0.0.1:9110
2019-04-08 14:19:53.648 [INF] DCRW: Attempting RPC client connection to dcrd:9109
2019-04-08 14:19:54.338 [INF] SYNC: Established connection to RPC server dcrd:9109
2019-04-08 14:19:54.422 [INF] SYNC: Headers synced through block 00000000000000000caf81e7d411b5711682d9a3af90dc3947c1fa2c188f7e14 height 331248
2019-04-08 14:19:54.423 [INF] SYNC: Transactions synced through block 00000000000000000caf81e7d411b5711682d9a3af90dc3947c1fa2c188f7e14 height 331248
panic: runtime error: index out of range

goroutine 22 [running]:
go.etcd.io/bbolt.(*leafPageElement).key(...)
        /home/peter/go/src/go.etcd.io/bbolt/page.go:120
go.etcd.io/bbolt.(*Cursor).nsearch.func2(0x1934, 0x33901)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:328 +0xac
sort.Search(0x3269, 0x2550b0c, 0xc)
        /usr/lib/go-1.12/src/sort/search.go:66 +0x54
go.etcd.io/bbolt.(*Cursor).nsearch(0x2550dc0, 0x28ed820, 0x20, 0x20)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:327 +0xb8
go.etcd.io/bbolt.(*Cursor).search(0x2550dc0, 0x28ed820, 0x20, 0x20, 0x32dd, 0x0)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:257 +0x158
go.etcd.io/bbolt.(*Cursor).searchPage(0x2550dc0, 0x28ed820, 0x20, 0x20, 0x49145000)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:308 +0x118
go.etcd.io/bbolt.(*Cursor).search(0x2550dc0, 0x28ed820, 0x20, 0x20, 0x2554, 0x0)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:265 +0x134
go.etcd.io/bbolt.(*Cursor).searchPage(0x2550dc0, 0x28ed820, 0x20, 0x20, 0x505d5000)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:308 +0x118
go.etcd.io/bbolt.(*Cursor).search(0x2550dc0, 0x28ed820, 0x20, 0x20, 0x99e4, 0x0)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:265 +0x134
go.etcd.io/bbolt.(*Cursor).searchPage(0x2550dc0, 0x28ed820, 0x20, 0x20, 0x51463000)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:308 +0x118
go.etcd.io/bbolt.(*Cursor).search(0x2550dc0, 0x28ed820, 0x20, 0x20, 0xa872, 0x0)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:265 +0x134
go.etcd.io/bbolt.(*Cursor).seek(0x2550dc0, 0x28ed820, 0x20, 0x20, 0x2, 0x5a5, 0x18f5c, 0x2416000, 0x73b1e8, 0x799d88, ...)
        /home/peter/go/src/go.etcd.io/bbolt/cursor.go:159 +0x70
go.etcd.io/bbolt.(*Bucket).Get(0x36813a0, 0x28ed820, 0x20, 0x20, 0x36813a0, 0x66c461c8, 0x36813a0)
        /home/peter/go/src/go.etcd.io/bbolt/bucket.go:260 +0x98
github.com/decred/dcrwallet/wallet/internal/bdb.(*bucket).Get(0x36813a0, 0x28ed820, 0x20, 0x20, 0x66c461c8, 0x36813a0, 0x3681380)
        /home/peter/go/src/github.com/decred/dcrwallet/wallet/internal/bdb/db.go:176 +0x34
github.com/decred/dcrwallet/wallet/udb.existsBlockHeader(0x66c461c8, 0x3681380, 0x28ed820, 0x20, 0x20, 0x3681380, 0x245e9a0, 0x3220000)
        /home/peter/go/src/github.com/decred/dcrwallet/wallet/udb/txdb.go:478 +0x74
github.com/decred/dcrwallet/wallet/udb.(*Store).BlockInMainChain(0x2866000, 0xa2f100, 0x247a830, 0x28ed820, 0x2550e74)
        /home/peter/go/src/github.com/decred/dcrwallet/wallet/udb/txmined.go:830 +0x80
github.com/decred/dcrwallet/wallet.(*Wallet).BlockInMainChain.func1(0xa2f100, 0x247a830, 0xa2f100, 0x247a830)
        /home/peter/go/src/github.com/decred/dcrwallet/wallet/wallet.go:514 +0x48
github.com/decred/dcrwallet/wallet/walletdb.View(0xa33858, 0x27fc3c0, 0x2550eb0, 0x0, 0x0)
        /home/peter/go/src/github.com/decred/dcrwallet/wallet/walletdb/interface.go:213 +0xa4
github.com/decred/dcrwallet/wallet.(*Wallet).BlockInMainChain(0x2424400, 0x28ed820, 0x0, 0x0, 0x0)
        /home/peter/go/src/github.com/decred/dcrwallet/wallet/wallet.go:513 +0x6c
github.com/decred/dcrwallet/chain.(*RPCSyncer).startupSync(0x281d0e0, 0xa333d8, 0x281d300, 0x3ff3b0, 0x4)
        /home/peter/go/src/github.com/decred/dcrwallet/chain/sync.go:507 +0x4bc
github.com/decred/dcrwallet/chain.(*RPCSyncer).Run.func1(0x4, 0x94f5f4)
        /home/peter/go/src/github.com/decred/dcrwallet/chain/sync.go:189 +0x68
golang.org/x/sync/errgroup.(*Group).Go.func1(0x24d4510, 0x281d340)
        /home/peter/go/src/golang.org/x/sync/errgroup/errgroup.go:57 +0x48
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/peter/go/src/golang.org/x/sync/errgroup/errgroup.go:54 +0x50
```

**Comment by jrick** [comment]
My guess is that this is some form of filesystem or memory corruption (it was explained on matrix that this is running on a rpi and sd card).

Also, it appears that you built dcrwallet from master without using modules, which is no longer supported.  Either move the dcrwallet directory outside of GOPATH, or build with GO111MODULE=on.

**Comment by peterzen** [comment]
Thanks for the help - closing this.
