### ISSUE TITLE
Peers temporarily continue to deliver block headers after sync context is canceled

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrwallet#1493]
Headers fetched from a peer are occasionally processed even after the sync context is canceled. This bug became obvious with the following scenario: closing the wallet database immediately after canceling a sync operation while headers were being fetched.

The crash report:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcf270c97]
goroutine 1147 [running]:
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/udb.fetchRawBlockHeader(0x0, 0x0, 0x9eff7454, 0x20, 0x20, 0x0, 0xb4, 0xb4, 0x0, 0x0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/udb/txdb.go:468 +0x17
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/udb.(*Store).GetBlockHeader(0x9e810018, 0xcfbac780, 0xa3e736e0, 0x9eff7454, 0x6d, 0x0, 0x0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/udb/txmined.go:813 +0x71
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet.(*Wallet).nextRequiredPoWDifficulty(0x9e938200, 0xcfbac780, 0xa3e736e0, 0xa57565b8, 0xa42b0000, 0x7d0, 0x7d0, 0x0, 0x0, 0xd31f2c4c, ...)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/difficulty.go:182 +0x455
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet.(*Wallet).validateHeaderChainDifficulties(0x9e938200, 0xcfbac780, 0xa3e736e0, 0xa42b0000, 0x7d0, 0x7d0, 0x2cf, 0xa42aa780, 0xcf59e321, 0xcf04084c, ...)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/difficulty.go:543 +0x1ba
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet.(*Wallet).ValidateHeaderChainDifficulties.func1(0xcfbac780, 0xa3e736e0, 0xcfbac780, 0xa3e736e0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/difficulty.go:510 +0x51
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/walletdb.View(0xcfbae9e0, 0x9ebda700, 0x9e836e68, 0x0, 0x0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/walletdb/interface.go:213 +0x9d
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet.(*Wallet).ValidateHeaderChainDifficulties(0x9e938200, 0xa42b0000, 0x7d0, 0x7d0, 0x0, 0x0, 0x0, 0xa5644000, 0x7d0, 0x7d0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/wallet/difficulty.go:508 +0x8e
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv.(*Syncer).getHeaders(0x9ec183f0, 0xcfbae900, 0x9ec38680, 0x9ebdc000, 0x1, 0x1)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv/sync.go:1081 +0x786
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv.(*Syncer).startupSync(0x9ec183f0, 0xcfbae900, 0x9ec38680, 0x9ebdc000, 0x0, 0x0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv/sync.go:1145 +0x26d
github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv.(*Syncer).connectToPersistent.func1.1(0x9ec183f0, 0xcfbae900, 0x9ec38680, 0x9ebdc000, 0x9e9327c0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv/sync.go:342 +0x33
created by github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv.(*Syncer).connectToPersistent.func1
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/decred/dcrwallet/spv/sync.go:341 +0x3fb
```

A solution would be to probably check if the sync context has been canceled before attempting to process fetched headers in `Syncer.getHeaders()`. Similar effort was done in #1241.

**Comment by jrick** [comment]
Unlikely that this is a dcrwallet problem.  Cancelling the SPV sync does not stop it immediately.  You must wait until the syncer's Run method exits (as well as any ongoing wallet usage that can result in open DB transactions).

**Comment by itswisdomagain** [comment]
After canceling the sync context, but without waiting for `Syncer.Run` to return, we do `walletLoader.UnloadWallet()`

The `UnloadWallet` function calls
```
walletLoader.wallet.Stop()
walletLoader.wallet.WaitForShutdown()
walletLoader.db.Close()
```
`wallet.WaitForShutdown()` is expected to block "until all wallet goroutines have finished executing" (according to the dcrwallet documentation on the function) before the db is closed.

Still, after the db is closed, the `dcrwallet/wallet/udb/txdb.fetchRawBlockHeader` function still attempts to access the database. The stacktrace in the issue description above reveals that that function is called from `dcrwallet/spv.(*Syncer).getHeaders`

**Comment by jrick** [comment]
https://github.com/decred/dcrwallet/blob/65571b9f655d3f744dbd609b79917e93035862cb/wallet/wallet.go#L440-L444

**Comment by itswisdomagain** [comment]
Resolved in https://github.com/raedahgroup/dcrlibwallet/pull/50/.

This was the key:
> You must wait until the syncer's Run method exits
