### ISSUE TITLE
validate address panic

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrwallet#1693]
Calling validate address using a 1 of 2 multisig address on testnet.

```
2020-03-14 01:16:06.893 [INF] RPCS: RPC method walletinfo invoked by 127.0.0.1:36882
2020-03-14 01:16:06.973 [INF] RPCS: RPC method accountsyncaddressindex invoked by 127.0.0.1:36882
2020-03-14 01:16:08.345 [INF] RPCS: RPC method validateaddress invoked by 127.0.0.1:36882
panic: interface conversion: *udb.scriptAddress is not udb.ManagedPubKeyAddress: missing method Index

goroutine 898 [running]:
decred.org/dcrwallet/wallet.(*managedP2PKHAddress).PubKey(0xc00007bac0, 0xfd6f40, 0xc00007bac0, 0x7f6050128468)
        /home/joe/git/dcrwallet/wallet/addresses.go:156 +0x44
decred.org/dcrwallet/internal/rpc/jsonrpc.(*Server).validateAddress(0xc0000b2b40, 0xfd4d40, 0xc000aa4150, 0xbaf540, 0xc000506570, 0xbaf540, 0xc000506570, 0x0, 0x0)
        /home/joe/git/dcrwallet/internal/rpc/jsonrpc/methods.go:3569 +0x3a1
decred.org/dcrwallet/internal/rpc/jsonrpc.lazyApplyHandler.func2(0x0, 0x0, 0x0)
        /home/joe/git/dcrwallet/internal/rpc/jsonrpc/methods.go:238 +0x193
decred.org/dcrwallet/internal/rpc/jsonrpc.(*Server).websocketClientRespond.func1(0xc0005020c8, 0xc00056b9c0, 0xc00007b740, 0xc0000ac320, 0xfd4d40, 0xc000aa4150)
        /home/joe/git/dcrwallet/internal/rpc/jsonrpc/server.go:436 +0xc2
created by decred.org/dcrwallet/internal/rpc/jsonrpc.(*Server).websocketClientRespond
        /home/joe/git/dcrwallet/internal/rpc/jsonrpc/server.go:433 +0x34e
```

**Comment by jrick** [comment]
https://github.com/decred/dcrwallet/blob/a9fa2485e111332f862be14480d7070598833bec/internal/rpc/jsonrpc/methods.go#L3552-L3569

Looks like it's falling into the wrong switch case for implementing the wrong interface.
