### ISSUE TITLE
rpc panic in unmarshal

### ISSUE THREAD

**Issue by degeri** [decred/dcrwallet#1754]
Same as https://github.com/decred/dcrd/issues/2217

JSON Request:

`{"jsonrpc":"1.0","method":0}`

```
 panic serving 127.0.0.1:49210: interface conversion: interface {} is float64, not string
goroutine 34 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000010978, 0xc000751f8e, 0xc000151c80)
	/usr/local/go/src/net/http/h2_bundle.go:5713 +0x16b
panic(0xc0eba0, 0xc00055f0b0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/decred/dcrd/dcrjson/v3.(*Request).UnmarshalJSON(0xc00007f4f0, 0xc000035200, 0x1c, 0x600, 0x7f64494ad848, 0xc00007f4f0)
	/home/rio/go/pkg/mod/github.com/decred/dcrd/dcrjson/v3@v3.0.1/jsonrpc.go:90 +0x526
encoding/json.(*decodeState).object(0xc00051e420, 0xbeb7c0, 0xc00007f4f0, 0x16, 0xc00051e448, 0xc00056ff7b)
	/usr/local/go/src/encoding/json/decode.go:626 +0x2082
encoding/json.(*decodeState).value(0xc00051e420, 0xbeb7c0, 0xc00007f4f0, 0x16, 0xc000060a10, 0x7a4e1d)
	/usr/local/go/src/encoding/json/decode.go:387 +0x6d
encoding/json.(*decodeState).unmarshal(0xc00051e420, 0xbeb7c0, 0xc00007f4f0, 0xc00051e448, 0x0)
	/usr/local/go/src/encoding/json/decode.go:180 +0x1f0
encoding/json.Unmarshal(0xc000035200, 0x1c, 0x600, 0xbeb7c0, 0xc00007f4f0, 0x600, 0x0)
	/usr/local/go/src/encoding/json/decode.go:107 +0x112
decred.org/dcrwallet/internal/rpc/jsonrpc.(*Server).postClientRPC(0xc0000aab40, 0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/home/rio/dcrwallet/internal/rpc/jsonrpc/server.go:537 +0x34f
decred.org/dcrwallet/internal/rpc/jsonrpc.NewServer.func2(0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/home/rio/dcrwallet/internal/rpc/jsonrpc/server.go:135 +0x381
net/http.HandlerFunc.ServeHTTP(0xc00001e780, 0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/usr/local/go/src/net/http/server.go:2012 +0x44
decred.org/dcrwallet/internal/rpc/jsonrpc.throttled.func1(0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/home/rio/dcrwallet/internal/rpc/jsonrpc/server.go:289 +0x19d
net/http.HandlerFunc.ServeHTTP(0xc0000e6b70, 0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000073500, 0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/usr/local/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0000aab40, 0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.initALPNRequest.ServeHTTP(0xfaf2a0, 0xc000093740, 0xc0000d5c00, 0xc0000aab40, 0xfac1e0, 0xc000010978, 0xc0000c2a00)
	/usr/local/go/src/net/http/server.go:3381 +0x8d
net/http.(*http2serverConn).runHandler(0xc000151c80, 0xc000010978, 0xc0000c2a00, 0xc00000ea80)
	/usr/local/go/src/net/http/h2_bundle.go:5720 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5454 +0x4e1
```

Fix on dcrd: https://github.com/decred/dcrd/pull/2218

**Comment by jrick** [comment]
This was fixed earlier by pulling in a newer dcrjson requirement.
