### ISSUE TITLE
addresses: locking order leads to deadlock

### ISSUE THREAD

**Issue by norwnd** [decred/dcrwallet#2199]
The issue is probably similar in spirit to  https://github.com/decred/dcrwallet/issues/1793.

I've been testing `dexc` with `testnets` on more-or-less latest master (+ some non-effectual commits of my own), here is [the exact commit](https://github.com/norwnd/dcrdex/commit/6f6d90bdfe3368cc429547a2c7b4cc15d4491ef0) when I encountered the deadlock, and it seems to be originating from `dcrwallet` (from what I gathered).

I had some active trades when I started `dexc` and `/login` page just wasn't loading for ~1 minute, tried refreshing it / opening it in another browser but nothing seemed to help, so I killed `dexc` with `kill -QUIT 1841` and got go-routine stacktraces, where many of them are blocked in places they probably  shouldn't be hanging for many minutes (like on `trackedTrade.mtx`).

Here is the full log I've got: [goroutine-dump.txt](https://github.com/decred/dcrwallet/files/10530246/goroutine-dump.txt)

and here is what I think caused the hanging:

```
goroutine 1652 [semacquire, 9 minutes]:
runtime.gopark(0x0?, 0x18?, 0x40?, 0xd4?, 0x10570e6?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc007554f80 sp=0xc007554f60 pc=0x10398b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.semacquire1(0xc00088e3fc, 0x8?, 0x3, 0x1)
	/usr/local/go/src/runtime/sema.go:150 +0x1fe fp=0xc007554fe8 sp=0xc007554f80 pc=0x104a75e
sync.runtime_SemacquireMutex(0x6f8e0bbcfbf7ead2?, 0xf9?, 0x100?)
	/usr/local/go/src/runtime/sema.go:77 +0x25 fp=0xc007555018 sp=0xc007554fe8 pc=0x1066dc5
sync.(*Mutex).lockSlow(0xc00088e3f8)
	/usr/local/go/src/sync/mutex.go:171 +0x165 fp=0xc007555068 sp=0xc007555018 pc=0x1081a85
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
go.etcd.io/bbolt.(*DB).beginRWTx(0xc00088e240)
	/Users/norwnd/go/pkg/mod/go.etcd.io/bbolt@v1.3.7-0.20220130032806-d5db64bdbfde/db.go:640 +0x77 fp=0xc0075550d8 sp=0xc007555068 pc=0x195eb57
go.etcd.io/bbolt.(*DB).Begin(0xc007555188?, 0x97?)
	/Users/norwnd/go/pkg/mod/go.etcd.io/bbolt@v1.3.7-0.20220130032806-d5db64bdbfde/db.go:589 +0x1d fp=0xc0075550f0 sp=0xc0075550d8 pc=0x195e85d
decred.org/dcrwallet/v2/wallet/internal/bdb.(*db).beginTx(0x13dcd14426ae3f53?, 0x8d?)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/internal/bdb/db.go:266 +0x19 fp=0xc007555118 sp=0xc0075550f0 pc=0x1b33a19
decred.org/dcrwallet/v2/wallet/internal/bdb.(*db).BeginReadWriteTx(0x2d22438?)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/internal/bdb/db.go:278 +0x1e fp=0xc007555138 sp=0xc007555118 pc=0x1b33b1e
decred.org/dcrwallet/v2/wallet.(*Wallet).persistReturnedChild.func1(0x0?, 0x0?, 0x2d25d60?)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/addresses.go:484 +0xca fp=0xc0075551f0 sp=0xc007555138 pc=0x1bd25aa
decred.org/dcrwallet/v2/wallet.(*Wallet).nextAddress(0xc0000fb860, {0x2d22438, 0xc0002a0500}, {0x2398066, 0x19}, 0xc0084c1b60, {0xc0084c6770, 0x7}, 0x0, 0x0, ...)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/addresses.go:615 +0xa3e fp=0xc0075553a8 sp=0xc0075551f0 pc=0x1bd36de
decred.org/dcrwallet/v2/wallet.(*Wallet).NewExternalAddress(0xc0084c8cc0?, {0x2d22438, 0xc0002a0500}, 0x7555480?, {0xc00846ab38, 0x1, 0x1})
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/addresses.go:746 +0xf3 fp=0xc007555440 sp=0xc0075553a8 pc=0x1bd4193
decred.org/dcrdex/client/asset/dcr.(*spvWallet).ExternalAddress(0xc0000f2370, {0x2d22438, 0xc0002a0500}, {0xc007839140?, 0x195?})
	/Users/norwnd/dcrdex/client/asset/dcr/spv.go:543 +0xab fp=0xc007555490 sp=0xc007555440 pc=0x1c8ebcb
decred.org/dcrdex/client/asset/dcr.(*ExchangeWallet).refundTx(0xc00069a500, {0xc00001a727?, 0x0?, 0xc00759f908?}, {0xc00001a682, 0x61, 0x195}, 0x0, {0x0, 0x0}, ...)
	/Users/norwnd/dcrdex/client/asset/dcr/dcr.go:3137 +0x9a8 fp=0xc0075556e0 sp=0xc007555490 pc=0x1c77ac8
decred.org/dcrdex/client/asset/dcr.(*ExchangeWallet).Refund(0xc00069a500, {0xc00001a727?, 0x0?, 0x0?}, {0xc00001a682?, 0xc0075237b8?, 0xc007523880?}, 0x1c1b83e?)
	/Users/norwnd/dcrdex/client/asset/dcr/dcr.go:3043 +0xd0 fp=0xc0075557d0 sp=0xc0075556e0 pc=0x1c76e90
decred.org/dcrdex/client/core.(*Core).refundMatches(0xc000344c00, 0xc000a88480, {0xc000027130, 0x1, 0x0?})
	/Users/norwnd/dcrdex/client/core/trade.go:3059 +0x519 fp=0xc007555980 sp=0xc0075557d0 pc=0x1f364d9
decred.org/dcrdex/client/core.(*Core).tick(0xc000344c00, 0xc000a88480)
	/Users/norwnd/dcrdex/client/core/trade.go:2029 +0x18c5 fp=0xc007555f60 sp=0xc007555980 pc=0x1f2b005
decred.org/dcrdex/client/core.(*Core).tickAsset.func1()
	/Users/norwnd/dcrdex/client/core/core.go:1159 +0x45 fp=0xc007555fe0 sp=0xc007555f60 pc=0x1ecc885
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc007555fe8 sp=0xc007555fe0 pc=0x106b4e1
created by decred.org/dcrdex/client/core.(*Core).tickAsset
	/Users/norwnd/dcrdex/client/core/core.go:1158 +0x277

goroutine 256 [semacquire, 9 minutes]:
runtime.gopark(0xc000c9a420?, 0xc0008a7788?, 0xe0?, 0xf6?, 0x10570e6?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc0008a7768 sp=0xc0008a7748 pc=0x10398b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.semacquire1(0xc0000fb9ac, 0xf0?, 0x3, 0x1)
	/usr/local/go/src/runtime/sema.go:150 +0x1fe fp=0xc0008a77d0 sp=0xc0008a7768 pc=0x104a75e
sync.runtime_SemacquireMutex(0x0?, 0xe0?, 0xc000c9a420?)
	/usr/local/go/src/runtime/sema.go:77 +0x25 fp=0xc0008a7800 sp=0xc0008a77d0 pc=0x1066dc5
sync.(*Mutex).lockSlow(0xc0000fb9a8)
	/usr/local/go/src/sync/mutex.go:171 +0x165 fp=0xc0008a7850 sp=0xc0008a7800 pc=0x1081a85
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
decred.org/dcrwallet/v2/wallet.(*Wallet).DiscoverActiveAddresses.func7({0x2d271f0, 0xc0085fc438})
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/discovery.go:931 +0x1ca fp=0xc0008a78c8 sp=0xc0008a7850 pc=0x1bfd14a
decred.org/dcrwallet/v2/wallet/walletdb.Update({0x2d22438, 0xc000cc6080}, {0x2d22780, 0xc00088e240}, 0xc0008a7ba8)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/walletdb/interface.go:249 +0x195 fp=0xc0008a7980 sp=0xc0008a78c8 pc=0x1b324d5
decred.org/dcrwallet/v2/wallet.(*Wallet).DiscoverActiveAddresses(0xc0000fb860, {0x2d22438, 0xc000cc6080}, {0x2d22710?, 0xc000c10000}, 0xc000c23f00?, 0x0, 0x64)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/discovery.go:908 +0x11fc fp=0xc0008a7e58 sp=0xc0008a7980 pc=0x1bfc6fc
decred.org/dcrwallet/v2/spv.(*Syncer).startupSync.func1(0xc000429560, {0x2d22438?, 0xc000cc6080}, 0xc000c10000?)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/spv/sync.go:1373 +0x146 fp=0xc0008a7ef0 sp=0xc0008a7e58 pc=0x1c610e6
decred.org/dcrwallet/v2/spv.(*Syncer).startupSync(0xc000429560, {0x2d22438?, 0xc000cc6080}, 0xc000c10000)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/spv/sync.go:1406 +0x3d0 fp=0xc0008a7f98 sp=0xc0008a7ef0 pc=0x1c60d90
decred.org/dcrwallet/v2/spv.(*Syncer).connectToCandidates.func1.2()
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/spv/sync.go:519 +0x37 fp=0xc0008a7fe0 sp=0xc0008a7f98 pc=0x1c59d17
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0008a7fe8 sp=0xc0008a7fe0 pc=0x106b4e1
created by decred.org/dcrwallet/v2/spv.(*Syncer).connectToCandidates.func1
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/spv/sync.go:518 +0x56b
```
- the 1st trace shows that `nextAddress` func tries to grab DB transaction lock (by calling `persist`) while holding `addressBuffersMu.Lock`
- the 2nd trace shows that in `DiscoverActiveAddresses` we acquire DB transaction lock first (via `walletdb.Update`) and then trying to acquire `addressBuffersMu.Lock` also (see **discovery.go:931**).

The hanging goroutines DEX spawned are probably blocked because of that deadlock ^ in `dcrwallet` package above, they all seem to be tied to `trackedTrade.mtx` in one way or another, and it is locked by goroutine that attempts to grab DB transaction lock like this:
```
goroutine 1652 [semacquire, 9 minutes]:
runtime.gopark(0x0?, 0x18?, 0x40?, 0xd4?, 0x10570e6?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc007554f80 sp=0xc007554f60 pc=0x10398b6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.semacquire1(0xc00088e3fc, 0x8?, 0x3, 0x1)
	/usr/local/go/src/runtime/sema.go:150 +0x1fe fp=0xc007554fe8 sp=0xc007554f80 pc=0x104a75e
sync.runtime_SemacquireMutex(0x6f8e0bbcfbf7ead2?, 0xf9?, 0x100?)
	/usr/local/go/src/runtime/sema.go:77 +0x25 fp=0xc007555018 sp=0xc007554fe8 pc=0x1066dc5
sync.(*Mutex).lockSlow(0xc00088e3f8)
	/usr/local/go/src/sync/mutex.go:171 +0x165 fp=0xc007555068 sp=0xc007555018 pc=0x1081a85
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
go.etcd.io/bbolt.(*DB).beginRWTx(0xc00088e240)
	/Users/norwnd/go/pkg/mod/go.etcd.io/bbolt@v1.3.7-0.20220130032806-d5db64bdbfde/db.go:640 +0x77 fp=0xc0075550d8 sp=0xc007555068 pc=0x195eb57
go.etcd.io/bbolt.(*DB).Begin(0xc007555188?, 0x97?)
	/Users/norwnd/go/pkg/mod/go.etcd.io/bbolt@v1.3.7-0.20220130032806-d5db64bdbfde/db.go:589 +0x1d fp=0xc0075550f0 sp=0xc0075550d8 pc=0x195e85d
decred.org/dcrwallet/v2/wallet/internal/bdb.(*db).beginTx(0x13dcd14426ae3f53?, 0x8d?)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/internal/bdb/db.go:266 +0x19 fp=0xc007555118 sp=0xc0075550f0 pc=0x1b33a19
decred.org/dcrwallet/v2/wallet/internal/bdb.(*db).BeginReadWriteTx(0x2d22438?)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/internal/bdb/db.go:278 +0x1e fp=0xc007555138 sp=0xc007555118 pc=0x1b33b1e
decred.org/dcrwallet/v2/wallet.(*Wallet).persistReturnedChild.func1(0x0?, 0x0?, 0x2d25d60?)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/addresses.go:484 +0xca fp=0xc0075551f0 sp=0xc007555138 pc=0x1bd25aa
decred.org/dcrwallet/v2/wallet.(*Wallet).nextAddress(0xc0000fb860, {0x2d22438, 0xc0002a0500}, {0x2398066, 0x19}, 0xc0084c1b60, {0xc0084c6770, 0x7}, 0x0, 0x0, ...)
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/addresses.go:615 +0xa3e fp=0xc0075553a8 sp=0xc0075551f0 pc=0x1bd36de
decred.org/dcrwallet/v2/wallet.(*Wallet).NewExternalAddress(0xc0084c8cc0?, {0x2d22438, 0xc0002a0500}, 0x7555480?, {0xc00846ab38, 0x1, 0x1})
	/Users/norwnd/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.8/wallet/addresses.go:746 +0xf3 fp=0xc007555440 sp=0xc0075553a8 pc=0x1bd4193
decred.org/dcrdex/client/asset/dcr.(*spvWallet).ExternalAddress(0xc0000f2370, {0x2d22438, 0xc0002a0500}, {0xc007839140?, 0x195?})
	/Users/norwnd/dcrdex/client/asset/dcr/spv.go:543 +0xab fp=0xc007555490 sp=0xc007555440 pc=0x1c8ebcb
decred.org/dcrdex/client/asset/dcr.(*ExchangeWallet).refundTx(0xc00069a500, {0xc00001a727?, 0x0?, 0xc00759f908?}, {0xc00001a682, 0x61, 0x195}, 0x0, {0x0, 0x0}, ...)
	/Users/norwnd/dcrdex/client/asset/dcr/dcr.go:3137 +0x9a8 fp=0xc0075556e0 sp=0xc007555490 pc=0x1c77ac8
decred.org/dcrdex/client/asset/dcr.(*ExchangeWallet).Refund(0xc00069a500, {0xc00001a727?, 0x0?, 0x0?}, {0xc00001a682?, 0xc0075237b8?, 0xc007523880?}, 0x1c1b83e?)
	/Users/norwnd/dcrdex/client/asset/dcr/dcr.go:3043 +0xd0 fp=0xc0075557d0 sp=0xc0075556e0 pc=0x1c76e90
decred.org/dcrdex/client/core.(*Core).refundMatches(0xc000344c00, 0xc000a88480, {0xc000027130, 0x1, 0x0?})
	/Users/norwnd/dcrdex/client/core/trade.go:3059 +0x519 fp=0xc007555980 sp=0xc0075557d0 pc=0x1f364d9
decred.org/dcrdex/client/core.(*Core).tick(0xc000344c00, 0xc000a88480)
	/Users/norwnd/dcrdex/client/core/trade.go:2029 +0x18c5 fp=0xc007555f60 sp=0xc007555980 pc=0x1f2b005
decred.org/dcrdex/client/core.(*Core).tickAsset.func1()
	/Users/norwnd/dcrdex/client/core/core.go:1159 +0x45 fp=0xc007555fe0 sp=0xc007555f60 pc=0x1ecc885
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc007555fe8 sp=0xc007555fe0 pc=0x106b4e1
created by decred.org/dcrdex/client/core.(*Core).tickAsset
	/Users/norwnd/dcrdex/client/core/core.go:1158 +0x277
```

cc @chappjc @buck54321 @JoeGruffins maybe you'd wanna cross-check me ^ on that.

**Comment by chappjc** [comment]
Please make an issue on the dcrwallet repo.  Your assessment looks correct.

**Comment by chappjc** [comment]
Oh this is the dcrwallet repo.  Derp.

**Comment by chappjc** [comment]
@norwnd were you going to look into the dcrwallet code?  If not, have you had a chance to look @jrick?  In a nutshell, while wallet is doing `DiscoverActiveAddresses`, you can deadlock it with a poorly timed `getnewaddress` because of the described lock ordering issue.

In dex, potentially we can work around this... although I'm pretty sure we were already waiting on `spv.(*Syncer).Synced`, but perhaps not on this path.

**Comment by norwnd** [comment]
> @norwnd were you going to look into the dcrwallet code?

I can give it a try, if there is no rush (can't promise anything within next few days, maybe in a couple of weeks).

**Comment by jrick** [comment]
your assessment looks correct, the addressBuffersMu lock should be moved outside of the db update.
