### ISSUE TITLE
missed > revoked in dcrwallet with multiple voting-only accounts

### ISSUE THREAD

**Issue by kfuchsia** [decred/dcrwallet#305]
Some missed tickets are not being revoked in my wallet with multiple voting-only accounts.

I am using the 0.2.0 release. I have tried restarting and restoring the wallet to no avail.

**Comment by alexlyp** [comment]
so you'll need to manually revoke them if they are not being automatically revoked.

here is a forum post discussing the procedure: 
https://forum.decred.org/threads/time-for-ticket-expires.3916/#post-21441

The idea is to createrawssrtx, sign that then send it.  Let me know if you need help constructing the commands for dcrctl.

**Comment by kfuchsia** [comment]
I am receiving a runtime error when signing:

```sh
$ dcrctl \
  -C ~/.dcrctl/wallet.conf \
  --wallet \
  createrawssrtx '[{"txid":"ticket_txid","vout":n,"tree":n}]'

$ dcrctl \
  -C ~/.dcrctl/wallet.conf \
  --wallet \
  signrawtransaction "result_of_above"
Post https://localhost:9110: EOF
```

dcrwallet output:

```
2016/08/03 10:03:40 http: panic serving [::1]:58794: runtime error: invalid memory address or nil pointer dereference
goroutine 146 [running]:
net/http.(*conn).serve.func1(0xc8204c8000)
        /usr/lib/go/src/net/http/server.go:1389 +0xc1
panic(0xd3f4e0, 0xc82000a190)
        /usr/lib/go/src/runtime/panic.go:443 +0x4e9
github.com/decred/dcrwallet/rpc/legacyrpc.signRawTransaction(0xb5a320, 0xc8200bef90, 0xc8204d8400, 0xc8203e6000, 0x0, 0x0, 0x0, 0x0)
        /src/github.com/decred/dcrwallet/rpc/legacyrpc/methods.go:3268 +0x23d6
github.com/decred/dcrwallet/rpc/legacyrpc.lazyApplyHandler.func2(0x0, 0x0, 0xc831544bc0)
        /src/github.com/decred/dcrwallet/rpc/legacyrpc/methods.go:233 +0xde
github.com/decred/dcrwallet/rpc/legacyrpc.(*Server).postClientRPC(0xc820090580, 0x7f47a99018b8, 0xc8203f4a90, 0xc820402700)
        /src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:614 +0xa56
github.com/decred/dcrwallet/rpc/legacyrpc.NewServer.func2(0x7f47a99018b8, 0xc8203f4a90, 0xc820402700)
        /src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:132 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8204710a0, 0x7f47a99018b8, 0xc8203f4a90, 0xc820402700)
        /usr/lib/go/src/net/http/server.go:1618 +0x3a
github.com/decred/dcrwallet/rpc/legacyrpc.throttled.func1(0x7f47a99018b8, 0xc8203f4a90, 0xc820402700)
        /src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:336 +0x23d
net/http.HandlerFunc.ServeHTTP(0xc82046d050, 0x7f47a99018b8, 0xc8203f4a90, 0xc820402700)
        /usr/lib/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82046ce70, 0x7f47a99018b8, 0xc8203f4a90, 0xc820402700)
        /usr/lib/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820090580, 0x7f47a99018b8, 0xc8203f4a90, 0xc820402700)
        /usr/lib/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8204c8000)
        /usr/lib/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2137 +0x44e
```

**Comment by kfuchsia** [comment]
After I issued the above command, dcrwallet became unresponsive to `stop` command, and unresponsive to SIGINT (`^C^C^C^C^C^C`). `kill -9` was required.
