### ISSUE TITLE
Crash on large number of tickets

### ISSUE THREAD

**Issue by JasonSome** [decred/dcrwallet#338]
Here is the log, when I tried to purchase ~2000 tickets on testnet:

```
10:45:52 2016-09-16 [INF] WLLT: The client has successfully connected to dcrd and is now handling websocket notifications
10:45:52 2016-09-16 [ERR] WLLT: Cannot handle chain server voting notification WinningTickets: Error encountered attempting to create vote using ticket e5411adfe805ef60891a33be84a3badea063e80ef17737d2415a34af6f4f0cf6: -22: TX rejected: already have transaction 4963e2513ec52dbb4e472c55840f7b3c47059fcf8597657aec5d6a0d23dd130c

10:45:52 2016-09-16 [ERR] WLLT: Cannot handle chain server voting notification WinningTickets: Error encountered attempting to create vote using ticket 59a55e99de6724bd28d5b740efb3e105da057c6cc984c2026785dc2147c831bc: -22: TX rejected: already have transaction 808aaa036719343398a1af3c55be78bfffca32b0e84fe33330ad1bc56208bb86

10:49:15 2016-09-16 [ERR] CHNS: Timeout waiting for session RPC
10:49:22 2016-09-16 [WRN] CHNS: Received unexpected reply: {"sessionid":9692787257560972208} (id 7674)
runtime: VirtualAlloc of 1048576 bytes failed with errno=1455
fatal error: runtime: cannot map pages in arena address space

runtime stack:
runtime.throw(0xc0802d, 0x30)
        C:/Users/User/go/src/runtime/panic.go:566 +0x9c
runtime.sysMap(0xc1d3a50000, 0x100000, 0xe19b01, 0x10f9b58)
        C:/Users/User/go/src/runtime/mem_windows.go:116 +0x12c
runtime.(*mheap).sysAlloc(0x10e00e0, 0x100000, 0x10e00f8)
        C:/Users/User/go/src/runtime/malloc.go:407 +0x381
runtime.(*mheap).grow(0x10e00e0, 0x1, 0x0)
        C:/Users/User/go/src/runtime/mheap.go:726 +0x69
runtime.(*mheap).allocSpanLocked(0x10e00e0, 0x1, 0xc042010d00)
        C:/Users/User/go/src/runtime/mheap.go:630 +0x4f9
runtime.(*mheap).alloc_m(0x10e00e0, 0x1, 0x19, 0x143038e0)
        C:/Users/User/go/src/runtime/mheap.go:515 +0xee
runtime.(*mheap).alloc.func1()
        C:/Users/User/go/src/runtime/mheap.go:579 +0x52
runtime.systemstack(0x380fdd8)
        C:/Users/User/go/src/runtime/asm_amd64.s:314 +0xb5
runtime.(*mheap).alloc(0x10e00e0, 0x1, 0x10000000019, 0x0)
        C:/Users/User/go/src/runtime/mheap.go:580 +0x7a
runtime.(*mcentral).grow(0x10e1ea0, 0x0)
        C:/Users/User/go/src/runtime/mcentral.go:210 +0x9b
runtime.(*mcentral).cacheSpan(0x10e1ea0, 0x143038e0)
        C:/Users/User/go/src/runtime/mcentral.go:91 +0x101
runtime.(*mcache).refill(0x3210490, 0xc100000019, 0x143038e0)
        C:/Users/User/go/src/runtime/mcache.go:121 +0xbc
runtime.(*mcache).nextFree.func1()
        C:/Users/User/go/src/runtime/malloc.go:505 +0x3a
runtime.systemstack(0xc042010d40)
        C:/Users/User/go/src/runtime/asm_amd64.s:298 +0x7e
runtime.mstart()
        C:/Users/User/go/src/runtime/proc.go:1079

goroutine 27 [running]:
runtime.systemstack_switch()
        C:/Users/User/go/src/runtime/asm_amd64.s:252 fp=0xc04218cf98 sp=0xc04218cf90
runtime.(*mcache).nextFree(0x3210490, 0x19, 0x1f4, 0xc1d3a4de00, 0xc04218d0d8)
        C:/Users/User/go/src/runtime/malloc.go:506 +0xb9 fp=0xc04218cff0 sp=0xc04218cf98
runtime.mallocgc(0x200, 0xabb800, 0xd83101, 0xd83133)
        C:/Users/User/go/src/runtime/malloc.go:658 +0x848 fp=0xc04218d090 sp=0xc04218cff0
runtime.makeslice(0xabb800, 0x0, 0x1f4, 0x14, 0xc04218d118, 0x18)
        C:/Users/User/go/src/runtime/slice.go:57 +0x82 fp=0xc04218d0e8 sp=0xc04218d090
github.com/decred/dcrwallet/vendor/github.com/decred/dcrd/txscript.payToPubKeyHashScript(0xc0420dc268, 0x14, 0x14, 0xc1d3a4de00, 0xc04218d1a0, 0x420b3f, 0x30, 0xb4b380)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/decred/dcrd/txscript/standard.go:677 +0x4a fp=0xc04218d150 sp=0xc04218d0e8
github.com/decred/dcrwallet/vendor/github.com/decred/dcrd/txscript.PayToAddrScript(0x108b600, 0xc0420dc260, 0xc1d3a4de00, 0x19, 0x1f4, 0x0, 0x0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/decred/dcrd/txscript/standard.go:1062 +0xf3 fp=0xc04218d1b0 sp=0xc04218d150
github.com/decred/dcrwallet/wallet.(*Wallet).purchaseTicket(0xc04246e800, 0x0, 0xbebc200, 0x0, 0x108b600, 0xc0421009c0, 0x0, 0x4fcbb4300, 0x0, 0x0, ...)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/wallet/createtx.go:1225 +0xafa fp=0xc04218d810 sp=0xc04218d1b0
github.com/decred/dcrwallet/wallet.(*Wallet).txCreator(0xc04246e800)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/wallet/wallet.go:962 +0xb80 fp=0xc04218df88 sp=0xc04218d810
runtime.goexit()
        C:/Users/User/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc04218df90 sp=0xc04218df88
created by github.com/decred/dcrwallet/wallet.(*Wallet).Start
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/wallet/wallet.go:422 +0xe4

goroutine 1 [chan receive, 9 minutes]:
main.walletMain(0x0, 0x0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/dcrwallet.go:182 +0x60e
main.main()
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/dcrwallet.go:38 +0x39

goroutine 18 [semacquire, 9 minutes]:
sync.runtime_notifyListWait(0xc0420378d0, 0x0)
        C:/Users/User/go/src/runtime/sema.go:267 +0x130
sync.(*Cond).Wait(0xc0420378c0)
        C:/Users/User/go/src/sync/cond.go:57 +0x87
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processItem(0xc04202c900, 0x0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:50 +0x9e
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processQueue(0xc04202c900)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:63 +0x3a
created by github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.newAsyncLoopLogger
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:40 +0x9d

goroutine 19 [semacquire, 9 minutes]:
sync.runtime_notifyListWait(0xc042037ad0, 0x0)
        C:/Users/User/go/src/runtime/sema.go:267 +0x130
sync.(*Cond).Wait(0xc042037ac0)
        C:/Users/User/go/src/sync/cond.go:57 +0x87
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processItem(0xc04202ca20, 0x0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:50 +0x9e
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processQueue(0xc04202ca20)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:63 +0x3a
created by github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.newAsyncLoopLogger
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:40 +0x9d

goroutine 7 [semacquire, 5 minutes]:
sync.runtime_notifyListWait(0xc042471250, 0xb)
        C:/Users/User/go/src/runtime/sema.go:267 +0x130
sync.(*Cond).Wait(0xc042471240)
        C:/Users/User/go/src/sync/cond.go:57 +0x87
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncAdaptiveLogger).processItem(0xc04245ab00, 0xc0532b6000, 0x0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_adaptivelogger.go:94 +0xa7
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncAdaptiveLogger).processQueue(0xc04245ab00)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_adaptivelogger.go:119 +0x3e
created by github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.newAsyncAdaptiveLogger
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_adaptivelogger.go:84 +0x1bc

goroutine 6 [syscall, 9 minutes]:
os/signal.signal_recv(0xc0423c7f88)
        C:/Users/User/go/src/runtime/sigqueue.go:116 +0x15e
os/signal.loop()
        C:/Users/User/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        C:/Users/User/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 9 [IO wait, 9 minutes]:
net.runtime_pollWait(0x3793f80, 0x72, 0xc042004d40)
        C:/Users/User/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).wait(0xc0424582f0, 0x72, 0xc042004d40, 0xc042451b58)
        C:/Users/User/go/src/net/fd_poll_runtime.go:73 +0x3f
net.(*ioSrv).ExecIO(0xc04205c018, 0xc0424581e0, 0xbccc4b, 0x8, 0xc0420f1a80, 0xc04254c180, 0x0, 0x0)
        C:/Users/User/go/src/net/fd_windows.go:171 +0x186
net.(*netFD).acceptOne(0xc042458180, 0xc042462460, 0x2, 0x2, 0xc0424581e0, 0xc042451d10, 0x42dd77, 0x381187c)
        C:/Users/User/go/src/net/fd_windows.go:529 +0x1f8
net.(*netFD).accept(0xc042458180, 0x0, 0x0, 0x0)
        C:/Users/User/go/src/net/fd_windows.go:559 +0x131
net.(*TCPListener).accept(0xc042454020, 0xc0424cc628, 0xc0424cc3f0, 0xb6d940)
        C:/Users/User/go/src/net/tcpsock_posix.go:132 +0x35
net.(*TCPListener).Accept(0xc042454020, 0xc000000001, 0xc0424cc600, 0xaee360, 0x10a8c70)
        C:/Users/User/go/src/net/tcpsock.go:222 +0x50
crypto/tls.(*listener).Accept(0xc0420f1940, 0xc0424cc5d0, 0xaee360, 0x10a8c70, 0xb45780)
        C:/Users/User/go/src/crypto/tls/tls.go:52 +0x3e
net/http.(*Server).Serve(0xc04207e6e0, 0x10868c0, 0xc0420f1940, 0x0, 0x0)
        C:/Users/User/go/src/net/http/server.go:2273 +0x1d5
github.com/decred/dcrwallet/rpc/legacyrpc.(*Server).serve.func1(0x10868c0, 0xc0420f1940, 0xc04207e6e0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:196 +0x111
created by github.com/decred/dcrwallet/rpc/legacyrpc.(*Server).serve
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:199 +0x7a

goroutine 10 [IO wait, 6 minutes]:
net.runtime_pollWait(0x3793ec0, 0x72, 0xc042298b50)
        C:/Users/User/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).wait(0xc04254c170, 0x72, 0xc042298b50, 0xc04244fb58)
        C:/Users/User/go/src/net/fd_poll_runtime.go:73 +0x3f
net.(*ioSrv).ExecIO(0xc04205c018, 0xc04254c060, 0xbccc4b, 0x8, 0xc0420e4440, 0xc04254c480, 0x0, 0x0)
        C:/Users/User/go/src/net/fd_windows.go:171 +0x186
net.(*netFD).acceptOne(0xc04254c000, 0xc042462d20, 0x2, 0x2, 0xc04254c060, 0x0, 0x4, 0x0)
        C:/Users/User/go/src/net/fd_windows.go:529 +0x1f8
net.(*netFD).accept(0xc04254c000, 0x0, 0x0, 0x0)
        C:/Users/User/go/src/net/fd_windows.go:559 +0x131
net.(*TCPListener).accept(0xc042454090, 0xc042454280, 0x10dafe0, 0x3210490)
        C:/Users/User/go/src/net/tcpsock_posix.go:132 +0x35
net.(*TCPListener).Accept(0xc042454090, 0x445e4e, 0xc04244fe28, 0x575f64, 0x465c60)
        C:/Users/User/go/src/net/tcpsock.go:222 +0x50
crypto/tls.(*listener).Accept(0xc0420f1980, 0xd88080, 0xc042122c80, 0x1088940, 0xc0424cc6c0)
        C:/Users/User/go/src/crypto/tls/tls.go:52 +0x3e
net/http.(*Server).Serve(0xc04207e6e0, 0x10868c0, 0xc0420f1980, 0x0, 0x0)
        C:/Users/User/go/src/net/http/server.go:2273 +0x1d5
github.com/decred/dcrwallet/rpc/legacyrpc.(*Server).serve.func1(0x10868c0, 0xc0420f1980, 0xc04207e6e0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:196 +0x111
created by github.com/decred/dcrwallet/rpc/legacyrpc.(*Server).serve
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:199 +0x7a

goroutine 11 [semacquire, 5 minutes]:
sync.runtime_Semacquire(0xc04246e9e4)
        C:/Users/User/go/src/runtime/sema.go:47 +0x37
sync.(*WaitGroup).Wait(0xc04246e9d8)
        C:/Users/User/go/src/sync/waitgroup.go:131 +0x9e
github.com/decred/dcrwallet/wallet.(*Wallet).WaitForShutdown(0xc04246e800)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/wallet/wallet.go:599 +0x74
main.rpcClientConnectLoop(0xc04207e6e0, 0xc04207cc00)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/dcrwallet.go:314 +0x32a
created by main.walletMain
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/dcrwallet.go:123 +0x9f7

goroutine 28 [chan receive, 6 minutes]:
github.com/decred/dcrwallet/wallet.(*Wallet).walletLocker(0xc04246e800)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/wallet/wallet.go:1164 +0x6bc
created by github.com/decred/dcrwallet/wallet.(*Wallet).Start
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/wallet/wallet.go:423 +0x106

goroutine 34 [select, 9 minutes]:
main.mainInterruptHandler()
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/signal.go:55 +0x28d
created by main.addInterruptHandler
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/signal.go:79 +0xe9

goroutine 35 [chan receive, 9 minutes]:
main.walletMain.func7(0xc04207e6e0)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/dcrwallet.go:177 +0x4e
created by main.walletMain
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/dcrwallet.go:179 +0x771

goroutine 29 [running]:
        goroutine running on other thread; stack unavailable
created by github.com/decred/dcrwallet/wallet.(*Wallet).SynchronizeRPC
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/wallet/wallet.go:459 +0x188

goroutine 51 [chan receive, 6 minutes]:
github.com/decred/dcrwallet/rpc/legacyrpc.purchaseTicket(0xa95d20, 0xc0422a4640, 0xc04246e800, 0x0, 0x0, 0xc0422a4500, 0xc0420eb140)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/methods.go:2208 +0x3d2
github.com/decred/dcrwallet/rpc/legacyrpc.lazyApplyHandler.func3(0xc04207e6e0, 0xc0422a45f0, 0xc0420eb140)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/methods.go:246 +0x8c
github.com/decred/dcrwallet/rpc/legacyrpc.(*Server).postClientRPC(0xc04207e6e0, 0x1087c40, 0xc04245e5b0, 0xc042250870)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:614 +0x262
github.com/decred/dcrwallet/rpc/legacyrpc.NewServer.func2(0x1087c40, 0xc04245e5b0, 0xc042250870)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:132 +0x140
net/http.HandlerFunc.ServeHTTP(0xc042004bf0, 0x1087c40, 0xc04245e5b0, 0xc042250870)
        C:/Users/User/go/src/net/http/server.go:1726 +0x4b
github.com/decred/dcrwallet/rpc/legacyrpc.throttled.func1(0x1087c40, 0xc04245e5b0, 0xc042250870)
        C:/Users/User/git/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:336 +0x209
net/http.HandlerFunc.ServeHTTP(0xc0424cc4b0, 0x1087c40, 0xc04245e5b0, 0xc042250870)
        C:/Users/User/go/src/net/http/server.go:1726 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0424cc480, 0x1087c40, 0xc04245e5b0, 0xc042250870)
        C:/Users/User/go/src/net/http/server.go:2022 +0x86
net/http.serverHandler.ServeHTTP(0xc04207e6e0, 0x1087c40, 0xc04245e5b0, 0xc042250870)
        C:/Users/User/go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc042122c80, 0x1088880, 0xc0425545c0)
        C:/Users/User/go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/Users/User/go/src/net/http/server.go:2293 +0x454
```

**Comment by jrick** [comment]
Is this 32 or 64-bit windows?  Virtual address space is very limited on 32-bit, and Go (along with pretty much any other garbage collected language that implements its own allocator) requires lots of address space.

**Comment by jrick** [comment]
Is this using one of our released binaries, or did you build it yourself?  If you built it, what version of Go did you compile it with?

**Comment by jrick** [comment]
@JasonSome has this issue ever happened again, or was this the only time?  Looks more like a go runtime bug than something we can fix directly.

**Comment by JasonSome** [comment]
@jrick, Sorry for not seeing your responses! You should have tagged me in! Anyway, yes, this is happening on testnet but only when trying to buy large chunks of tickets. Latest Go always used for my compilations, although this was the deployed binary. I am not sure whether this would be a Go runtime bug...

**Comment by jrick** [comment]
Do you have swap turned off by any chance? trying to think of why it's failing to allocate even on that small allocation, especially since you're on amd64 which has massive virtual address space.

**Comment by JasonSome** [comment]
Well, it is Windows and I haven't manually intervened to its storage, but should have enough RAM anyway...

**Comment by alexlyp** [comment]
Closing since this really isn't a valid test case and has been dormant since last year
