### ISSUE TITLE
Panic observed during chain reorganization at startup after none of the notified blocks attached to the main chain

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#525]
```
jcv@triforce tmp $ dcrwallet --testnet --experimentalrpclisten=127.0.0.1:19112 --noinitialload --tlscurve=P-256 --onetimetlskey --appdata=~/.config/decrediton
07:46:44 2017-01-17 [INF] DCRW: Version 0.7.0-beta
07:46:44 2017-01-17 [INF] DCRW: Generating TLS certificates...
07:46:44 2017-01-17 [INF] DCRW: Done generating TLS certificates
07:46:44 2017-01-17 [INF] DCRW: Legacy RPC server disabled (requires username and password)
07:46:44 2017-01-17 [INF] DCRW: Experimental RPC server listening on 127.0.0.1:19112
07:47:10 2017-01-17 [INF] WLLT: Opened wallet
07:47:10 2017-01-17 [INF] CHNS: Established connection to RPC server 127.0.0.1:19109
07:47:10 2017-01-17 [INF] WLLT: Fetching headers
07:47:11 2017-01-17 [INF] WLLT: Fetched 424 new header(s)
07:47:14 2017-01-17 [INF] WLLT: The wallet has been temporarily unlocked
07:47:14 2017-01-17 [INF] WLLT: Beginning a rescan of active addresses using the daemon. This may take a while.
07:47:14 2017-01-17 [INF] WLLT: The last used account was 0. Beginning a rescan for all active addresses in known accounts.
07:47:14 2017-01-17 [INF] WLLT: Successfully synchronized the address manager to external address Tsi9JHoMwi42xSsnekJosje7Gdj49MH6dvv (key index 8) for account 0
07:47:14 2017-01-17 [INF] WLLT: Successfully synchronized the address manager to internal address TsckLHRwBEtt6g5hyN9TNmf4wZqyEFY5EGC (key index 0) for account 0
07:47:14 2017-01-17 [INF] WLLT: Successfully synchronized wallet accounts to account number 0.
07:47:14 2017-01-17 [INF] WLLT: The wallet has been locked.
07:47:14 2017-01-17 [INF] WLLT: The client has successfully connected to dcrd and is now handling websocket notifications
07:47:16 2017-01-17 [INF] WLLT: Loading active addresses and unspent outputs...
07:47:16 2017-01-17 [INF] WLLT: Registering for transaction notifications for 50 address(es) and 0 output(s)
07:49:11 2017-01-17 [INF] WLLT: Connecting block 0000000003949029e6606bf7d861a660af163564341c92c25f477b1e5560213c, height 249762
07:49:11 2017-01-17 [ERR] WLLT: Failed to process consensus server notification (name: `blockconnected`, detail: `header is not a direct child of the current tip block`)
07:49:29 2017-01-17 [INF] WLLT: Connecting block 00000000011d49cf41b1f150b83c04a60f57eebecd4cd1baa4a997aa552c90ce, height 249763
07:49:29 2017-01-17 [ERR] WLLT: Failed to process consensus server notification (name: `blockconnected`, detail: `header is not a direct child of the current tip block`)
07:54:48 2017-01-17 [INF] WLLT: Connecting block 0000000005cecdd5a5d52817bb538a6bbf0078baf764f353b484863493b3f88f, height 249764
07:54:48 2017-01-17 [ERR] WLLT: Failed to process consensus server notification (name: `blockconnected`, detail: `header is not a direct child of the current tip block`)
07:58:13 2017-01-17 [INF] WLLT: Reorganization detected!
panic: runtime error: makeslice: len out of range

goroutine 85 [running]:
panic(0xaf7f40, 0xc420012fd0)
        /home/jcv/code/golang/src/runtime/panic.go:500 +0x1a1
github.com/decred/dcrwallet/wallet.(*Wallet).switchToSideChain(0xc420432240, 0x10926c0, 0xc420034068, 0xc4202b0601, 0x2, 0x2)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:220 +0x1f3
github.com/decred/dcrwallet/wallet.(*Wallet).onBlockConnected(0xc420432240, 0x10926c0, 0xc420034068, 0xc4204d8240, 0xb4, 0xb4, 0x10ff9d8, 0x0, 0x0, 0x0, ...)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:304 +0x546
github.com/decred/dcrwallet/wallet.(*Wallet).handleConsensusRPCNotifications.func1(0x10926c0, 0xc420034068, 0xc420034068, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:39 +0x7e
github.com/decred/dcrwallet/walletdb.Update(0x10907c0, 0xc4204ee5a0, 0xc420611f20, 0xc420611ef0, 0x1)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/walletdb/interface.go:219 +0x6f
github.com/decred/dcrwallet/wallet.(*Wallet).handleConsensusRPCNotifications(0xc420432240, 0xc4202b4380)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:40 +0x3c4
github.com/decred/dcrwallet/wallet.(*Wallet).AssociateConsensusRPC.func1(0xc420432240, 0xc4202b4380)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:74 +0x35
created by github.com/decred/dcrwallet/wallet.(*Wallet).AssociateConsensusRPC
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:76 +0xe7
jcv@triforce tmp $ 
```

The interesting line: https://github.com/decred/dcrwallet/blob/1c4f6d43994038019f8f3e6dd42e40f49e4ebc0c/wallet/chainntfns.go#L220

Reported by @jcvernaleo

**Comment by jrick** [comment]
The failed to attach blocks appear to be due to a bug in decrediton which performed the startup operations in the wrong order, causing a block to be missed and then all later blocks failing to attach.  The panic might still be a real bug and we should write some defensive code to prevent it.

**Comment by marsmensch** [comment]
Don't know if it the same problem, but probably related. A dcrd linux installation (on a Pine64) crashes on me since a couple of days. 

> -- Unit decred.service has begun starting up.
> Jan 27 11:46:39 pine64 dcrd[5603]: 11:46:39 2017-01-27 [INF] DCRD: Version 0.7.0-beta
> Jan 27 11:46:39 pine64 dcrd[5603]: 11:46:39 2017-01-27 [INF] DCRD: Home dir: /home/ubuntu/.dcrd
> Jan 27 11:46:39 pine64 dcrd[5603]: 11:46:39 2017-01-27 [INF] DCRD: Loading block database from '/home/ubuntu/.dcrd/data/mainnet/blocks_ffldb'
> Jan 27 11:46:40 pine64 dcrd[5603]: 11:46:40 2017-01-27 [INF] DCRD: Block database loaded
> Jan 27 11:46:40 pine64 dcrd[5603]: 11:46:40 2017-01-27 [DBG] AMGR: Skipping local address: address 127.0.0.1 is not routable
> Jan 27 11:46:40 pine64 dcrd[5603]: 11:46:40 2017-01-27 [DBG] AMGR: Skipping local address: address 192.168.1.42 is not routable
> Jan 27 11:46:40 pine64 dcrd[5603]: 11:46:40 2017-01-27 [DBG] AMGR: Skipping local address: address ::1 is not routable
> Jan 27 11:46:40 pine64 dcrd[5603]: 11:46:40 2017-01-27 [DBG] AMGR: Skipping local address: address fe80::34c9:e3ff:fef1:b805 is not routable
> Jan 27 11:46:40 pine64 dcrd[5603]: 11:46:40 2017-01-27 [INF] INDX: Exists address index is enabled
> Jan 27 11:46:41 pine64 dcrd[5603]: 11:46:41 2017-01-27 [INF] DCRD: Gracefully shutting down the database...
> Jan 27 11:46:41 pine64 dcrd[5603]: 11:46:41 2017-01-27 [INF] DCRD: Shutdown complete
> Jan 27 11:46:41 pine64 dcrd[5603]: panic: runtime error: index out of range [recovered]
> Jan 27 11:46:41 pine64 dcrd[5603]:         panic: runtime error: index out of range
> Jan 27 11:46:41 pine64 dcrd[5603]: goroutine 1 [running]:
> Jan 27 11:46:41 pine64 dcrd[5603]: panic(0x6cc1c0, 0x4420010080)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/golang/src/runtime/panic.go:500 +0x390
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/database/ffldb.rollbackOnPanic(0x44202d2750)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/database/ffldb/db.go:1890 +0x74
> Jan 27 11:46:41 pine64 dcrd[5603]: panic(0x6cc1c0, 0x4420010080)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/golang/src/runtime/panic.go:458 +0x4c0
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/database/ffldb.(*transaction).nextBucketID(0x44202d2750, 0x0, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/database/ffldb/db.go:1110 +0x98
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/database/ffldb.(*bucket).CreateBucket(0x44204f6cb0, 0xbb0170, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/database/ffldb/db.go:653 +0x93c
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/blockchain.(*BlockChain).createChainState.func1(0xbbd540, 0x44202d2750, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/blockchain/chainio.go:1292 +0x8c
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/database/ffldb.(*db).Update(0x44200cc980, 0x4420454bc0, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/database/ffldb/db.go:1947 +0xd8
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/blockchain.(*BlockChain).createChainState(0x4422564000, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/blockchain/chainio.go:1287 +0x34c
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/blockchain.(*BlockChain).initChainState(0x4422564000, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/blockchain/chainio.go:1481 +0x12c
> Jan 27 11:46:41 pine64 dcrd[5603]: github.com/decred/dcrd/blockchain.New(0x44204d5298, 0x4420d946c0, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/blockchain/chain.go:2193 +0x464
> Jan 27 11:46:41 pine64 dcrd[5603]: main.newBlockManager(0x4421c44500, 0xbb8100, 0x442252b4d0, 0x0, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/blockmanager.go:2740 +0x41c
> Jan 27 11:46:41 pine64 dcrd[5603]: main.newServer(0x44204f6380, 0x1, 0x1, 0xbba520, 0x44200cc980, 0xbfa1e0, 0x0, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/server.go:2595 +0x1d94
> Jan 27 11:46:41 pine64 dcrd[5603]: main.dcrdMain(0x0, 0x0, 0x0)
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/dcrd.go:166 +0xf2c
> Jan 27 11:46:41 pine64 dcrd[5603]: main.main()
> Jan 27 11:46:41 pine64 dcrd[5603]:         /home/jcv/code/go/src/github.com/decred/dcrd/dcrd.go:230 +0x104
> Jan 27 11:46:41 pine64 systemd[1]: decred.service: Control process exited, code=exited status=2
> Jan 27 11:46:41 pine64 systemd[1]: Failed to start Decred currency daemon.
> -- Subject: Unit decred.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

**Comment by dajohi** [comment]
```diff
diff --git a/wallet/chainntfns.go b/wallet/chainntfns.go
index 34cdea8..1a2d0af 100644
--- a/wallet/chainntfns.go
+++ b/wallet/chainntfns.go
@@ -215,6 +215,13 @@ func (w *Wallet) switchToSideChain(dbtx walletdb.ReadWriteTx) (*MainTipChangedNo
 
        _, tipHeight := w.TxStore.MainChainTip(txmgrNs)
 
+       if tipHeight < sideChainForkHeight+1 {
+               str := fmt.Sprintf("tipHeight < sideChaninForkHeight+1: %v < %v",
+                       tipHeight, sideChainForkHeight+1)
+               log.Errorf(str)
+               return nil, errors.New(str)
+       }
+
        chainTipChanges := &MainTipChangedNotification{
                AttachedBlocks: make([]*chainhash.Hash, len(sideChain)),
                DetachedBlocks: make([]*chainhash.Hash, tipHeight-sideChainForkHeight+1),
```

**Comment by jrick** [comment]
@marsmensch looks completely unrelated, this is a dcrwallet crash while yours is dcrd.  Could you please open an issue in the dcrd repo?

**Comment by jrick** [comment]
@dajohi the correct check would be to see whether `sideChainForkHeight < tipHeight + 1`

**Comment by dajohi** [comment]
would still panic if sideChainForkHeight == tipHeight

**Comment by jrick** [comment]
uh.. no. it would allocate a slice of length 1.

**Comment by dajohi** [comment]
definitely morning.

**Comment by jrick** [comment]
The cause of the panic here is that we are building up a side chain (and trying to switch to it after dcrd says the reorganization is complete) that starts *beyond* the current main chain tip.  This happened due to a missed block at startup because of a startup flaw from decrediton.  At this point the wallet is already mostly unusable because it will never sync to the best block.

As I see it, we could handle this by doing:

1. Nothing. This is a "bug" that is caused by other bugs and i'm not convinced that continuing to run the program even when a block was missed is the best course of action.

2. Add the above sanity check but still panic with a more descriptive message.

3. Add the sanity check and do nothing, keep running, and eventually bomb on OOM because of the giant side chain that will get built up in memory.

4. When creating a new sidechain, check that it actually does fork at a block that is already saved by the wallet.  If it does not, do not create the side chain.  This will leave the wallet running and it won't bomb on OOM (at least not for this reason).

I sort of think that panicing is still the best course of action here, since the wallet is not capable of performing its task because of the missed block and it should not pretend like everything is hunky dory.

**Comment by jcvernaleo** [comment]
I'm kind of in favor of option 2.  I agree panic is the correct thing to do but a better error message is always welcome.

**Comment by Louis-Xavier** [comment]
any luck resolving this issue and releasing a new binary for dcrwallet ?

**Comment by jrick** [comment]
@Louis-Xavier what version of the software did you hit this issue on?  It should be impossible to hit, unless there are bugs elsewhere.

**Comment by Louis-Xavier** [comment]
Hi,
i'm upgrading from 0.8.2 to 1.0.1 with the dcrinstaller. I've tried both 32bit and 64bit and I've the issue.

**Comment by jrick** [comment]
That is a different bug (the issue you already opened).  This is/was an unrelated issue.

**Comment by jrick** [comment]
Sidechain management has been completely redone for the SPV changes and this should not be an issue anymore.
