### ISSUE TITLE
panic: switchToSideChain

### ISSUE THREAD

**Issue by dajohi** [decred/dcrwallet#940]
```
9d123f95c6145b8b0954af8a6eb77cb6f67ef1540d33fe9a72bb bits: 5)
2017-09-25 23:05:08.218 [ERR] WLLT: Failed to process consensus server notification (name: `relevanttxaccepted`, detail: `unmined transaction bf5126c4413ec9eca2b71bd402cceed806f1d9209c4eb29e070291d18cd356b1 is a double spend of unmined transaction d402ff3c00909d123f95c6145b8b0954af8a6eb77cb6f67ef1540d33fe9a72bb`)
2017-09-25 23:05:44.617 [INF] WLLT: Reorganization detected!
2017-09-25 23:05:44.617 [INF] WLLT: Old top block hash: 0000000000e5cb930b8da39ab85faa1dee19c1ddbb3309501c6afd0346f794fa
2017-09-25 23:05:44.617 [INF] WLLT: Old top block height: 140023
2017-09-25 23:05:44.617 [INF] WLLT: New top block hash: 00000000016ada511b8714a6800e862e31ef5513d965ab21240c20a16721a183
2017-09-25 23:05:44.617 [INF] WLLT: New top block height: 140024
2017-09-25 23:05:44.637 [INF] WLLT: Adding block 000000000258cea67a020865beb3f351cafb89c95dfeb77567dd9b79404b7138 (height 140023) to sidechain
2017-09-25 23:05:47.113 [INF] WLLT: Adding block 00000000016ada511b8714a6800e862e31ef5513d965ab21240c20a16721a183 (height 140024) to sidechain
panic: runtime error: makeslice: len out of range

goroutine 53 [running]:
github.com/decred/dcrwallet/wallet.(*Wallet).switchToSideChain(0xc4201aa200, 0x10bd000, 0xc420608170, 0x8f90f0, 0xc42040e5a0, 0xc420bb4b01)
        /home/dhill/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:165 +0x26b
github.com/decred/dcrwallet/wallet.(*Wallet).onBlockConnected.func1(0x10bd000, 0xc420608170, 0xc420608170, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:251 +0x4b
github.com/decred/dcrwallet/walletdb.Update(0x10bb1c0, 0xc42040e5a0, 0xc420157c78, 0xc420c67f01, 0x2)
        /home/dhill/.go/src/github.com/decred/dcrwallet/walletdb/interface.go:219 +0x6f
github.com/decred/dcrwallet/wallet.(*Wallet).onBlockConnected(0xc4201aa200, 0xc420aca180, 0xb4, 0xb4, 0xc420c67b40, 0x1, 0x1, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:249 +0x553
github.com/decred/dcrwallet/wallet.(*Wallet).handleConsensusRPCNotifications(0xc4201aa200, 0xc4201463f0)
        /home/dhill/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:36 +0x373
github.com/decred/dcrwallet/wallet.(*Wallet).handleChainNotifications(0xc4201aa200, 0xc4201463f0)
        /home/dhill/.go/src/github.com/decred/dcrwallet/wallet/chainntfns.go:100 +0x60
created by github.com/decred/dcrwallet/wallet.(*Wallet).SynchronizeRPC
        /home/dhill/.go/src/github.com/decred/dcrwallet/wallet/wallet.go:556 +0x178
```

**Comment by jrick** [comment]
#525
